export const SAVE_NEWS_DATA = "SAVE_NEWS_DATA";
export const SAVE_NEWS_LIST = "SAVE_NEWS_LIST";
export const CLEAR_NEWS_LIST = "CLEAR_NEWS_LIST";
export const SAVE_NEWS_INDEX = "SAVE_NEWS_INDEX";
export const REQUEST_NEWS_DATA = "REQUEST_NEWS_DATA";
export const SUCCESS_NEWS_DATA = "SUCCESS_NEWS_DATA";
export const FAILURE_NEWS_DATA = "FAILURE_NEWS_DATA";



